COLUMNS = {'Magnitude_uncertainty': 'magnitude_uncertainty',
           'Location': 'location',
           'Location_uncertainty': 'location_uncertainty_km',
           'Depth': 'depth_km',
           'Depth_uncertainty': 'depth_uncertainty_km',
           'Origin Time': 'origin_time',
           'Number of Stations': 'num_of_stations',
           'Number of Phases': 'num_of_phases',
           'Minimum Distance': 'minimum_distance_km',
           'Travel Time Residual': 'travel_time_residual_sec',
           'Azimuthal Gap': 'azimuthal_gap_deg',
           'FE Region': 'fe_region',
           'Review Status': 'review_status',
           'Catalog': 'catalog',
           'Contributor': 'contributor'
           }